ln -fi cputemp.sh ~/
ln -fi date.sh ~/
ln -fi dropbox_echo.sh ~/
ln -fi mpd.sh ~/
ln -fi .vimrc ~/
ln -fi volume.sh ~/
ln -fi .xinitrc ~/
ln -fi .xmobarrc ~/
ln -fi .zshrc ~/
ln -fi .config/Terminal/terminalrc ~/.config/Terminal/terminalrc
ln -fi .xmonad/xmonad.hs ~/.xmonad/xmonad.hs
