ln -sfi /home/vishnu/dotfiles/cputemp.sh /home/vishnu/ 
ln -sfi /home/vishnu/dotfiles/battery.sh /home/vishnu/ 
ln -sfi /home/vishnu/dotfiles/date.sh  /home/vishnu/
ln -sfi /home/vishnu/dotfiles/dropbox_echo.sh /home/vishnu/
ln -sfi /home/vishnu/dotfiles/mpd.sh /home/vishnu/
ln -sfi /home/vishnu/dotfiles/.vimrc /home/vishnu/
ln -sfi /home/vishnu/dotfiles/volume.sh /home/vishnu/
ln -sfi /home/vishnu/dotfiles/.xinitrc /home/vishnu/
ln -sfi /home/vishnu/dotfiles/.xmobarrc /home/vishnu/
ln -sfi /home/vishnu/dotfiles/.zshrc /home/vishnu/
ln -sfi /home/vishnu/dotfiles/.config/Terminal/terminalrc /home/vishnu/.config/Terminal/terminalrc
ln -sfi /home/vishnu/dotfiles/.xmonad/xmonad.hs /home/vishnu/.xmonad/xmonad.hs
ln -sfi /home/vishnu/dotfiles/.Xresources /home/vishnu/
