ln -sfi ~/dotfiles/cputemp.sh ~/
ln -sfi ~/dotfiles/date.sh ~/
ln -sfi ~/dotfiles/dropbox_echo.sh ~/
ln -sfi ~/dotfiles/mpd.sh ~/
ln -sfi ~/dotfiles/.vimrc ~/
ln -sfi ~/dotfiles/volume.sh ~/
ln -sfi ~/dotfiles/.xinitrc ~/
ln -sfi ~/dotfiles/.xmobarrc ~/
ln -sfi ~/dotfiles/.zshrc ~/
ln -sfi /home/vishnu/dotfiles/.xmonad/xmonad.hs ~/.xmonad/
ln -sfi /home/vishnu/dotfiles/.mpd/mpd.conf ~/.mpd
ln -sfi /home/vishnu/dotfiles/.ncmpcppc /home/vishnu/
