#!/bin/sh

#~/.xinitrc

#Executed by startx (run your window manager from here)

xsetroot -cursor_name left_ptr
/usr/bin/xscreensaver -no-splash &
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 4 --transparent true --alpha 0 --tint 0x101112 --height 26 &  
nm-applet &
sh ~/.fehbg &
##dropbox start &
xbacklight -set 50 &
compton --vsync opengl -cb
exec dbus-launch xmonad
